version: "3"
services:
  social-media-app:
    container_name: social-media-app
    image: omarmadara7/social-media-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
