# fly.toml - Customized configuration

# Application name (used to create the default hostname)
app = "my-fake-book"

# Primary region for deployment (replace 'cdg' with your desired Fly Region code)
primary_region = "cdg"

# Processes configuration
[[processes]]
  type = "web"
  command = "npm start"  # Adjust based on your client app setup
  dir = "client"  # Directory where your client source code resides

[[processes]]
  type = "background"
  command = "node server.js"  # Adjust based on your server setup
  dir = "server"  # Directory where your server source code resides

# Ports configuration (optional)
# You can customize ports as needed for your app and database

# Environment variables (optional)
[env]
PORT = "8080"
MONGO_URI = "mongodb+srv://OmarMostafa:ooooooo7@cluster0.ebavy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

# Experimental settings (optional)
auto_rollback = true  # Enable auto-rollback on failed deploys

# Services configuration (optional)
[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.ports]
    port = 80
    handlers = ["http"]

# Secrets (optional)
# Add secrets using 'flyctl secrets set' command.
# Example:
# flyctl secrets set MONGO_PASSWORD=mysecretpassword
